#!/usr/bin/env bash
set -ex
GOOS=linux GOARCH=amd64 go install qiniu.com/argus/cmd/feature_group_private/dbstorage
cp $QBOXROOT/bin/dbstorage .
cp $QBOXROOT/src/qiniu.com/argus/cmd/feature_group_private/dbstorage/dbstorage.conf .
